name: PrivacyGames
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cudatoolkit=11.1.1
  - intel-openmp=2022.0.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libuv=1.40.0
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - mkl=2022.0.1
  - ncurses=6.3
  - ninja=1.10.2
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.8.13
  - python_abi=3.8
  - pytorch=1.9.0
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.38.0
  - tbb=2021.3.0
  - tk=8.6.11
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - adal==1.2.7
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - argcomplete==1.12.3
    - artifacts-keyring==0.3.1
    - async-timeout==4.0.2
    - attrs==21.4.0
    - azure-common==1.1.28
    - azure-core==1.21.1
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==8.2.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-keyvault==9.3.0
    - azure-mgmt-resource==20.1.0
    - azure-mgmt-storage==19.1.0
    - azureml-core==1.39.0.post1
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.1.0
    - contextlib2==21.6.0
    - cryptography==36.0.2
    - datasets==1.18.4
    - deprecated==1.2.13
    - dill==0.3.4
    - docker==5.0.3
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - grpcio==1.43.0
    - huggingface-hub==0.4.0
    - humanfriendly==10.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - iniconfig==1.1.1
    - isodate==0.6.1
    - jeepney==0.7.1
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonpickle==2.1.0
    - jsonschema==4.4.0
    - keyring==23.5.0
    - knack==0.9.0
    - msal==1.17.0
    - msal-extensions==0.3.1
    - msgpack==1.0.3
    - msrest==0.6.21
    - msrestazure==0.6.4
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - ndg-httpsclient==0.5.1
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opacus==0.15.0
    - opacus-utils==0.2.5
    - --extra-index-url https://pkgs.dev.azure.com/ii-m365/_packaging/ii-m365/pypi/simple
    - packaging==21.3
    - pandas==1.4.1
    - paramiko==2.10.3
    - pathspec==0.9.0
    - pkginfo==1.8.2
    - pluggy==1.0.0
    - portalocker==2.4.0
    - protobuf==3.19.4
    - prv-accountant==0.1.1.post1
    - py==1.11.0
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pycparser==2.21
    - pygments==2.11.2
    - pyjwt==2.3.0
    - pynacl==1.5.0
    - pyopenssl==21.0.0
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - pytest==7.1.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - ray==1.11.0
    - redis==4.2.0
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - sacremoses==0.0.49
    - scipy==1.8.0
    - secretstorage==3.3.1
    - seval==1.1.0
    - six==1.16.0
    - tabulate==0.8.9
    - tensorboardx==2.5
    - tokenizers==0.11.6
    - tomli==2.0.1
    - tqdm==4.63.1
    - transformers==4.17.0
    - urllib3==1.26.7
    - websocket-client==1.3.1
    - wrapt==1.14.0
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.7.0
