name: ComponentEnvironment
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.3.18
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.8.12
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.38.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - adal==1.2.7
    - argcomplete==1.12.3
    - azure-common==1.1.28
    - azure-core==1.21.1
    - azure-graphrbac==0.61.1
    - azure-identity==1.7.0
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==8.2.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-keyvault==9.3.0
    - azure-mgmt-resource==20.1.0
    - azure-mgmt-storage==19.1.0
    - azureml-core==1.39.0.post1
    - azureml-dataprep==2.27.1
    - azureml-dataprep-native==38.0.0
    - azureml-dataprep-rslex==2.3.1
    - azureml-dataset-runtime==1.39.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - cloudpickle==2.0.0
    - contextlib2==21.6.0
    - cryptography==36.0.2
    - distro==1.7.0
    - docker==5.0.3
    - dotnetcore2==2.1.23
    - humanfriendly==10.0
    - idna==3.3
    - isodate==0.6.1
    - jeepney==0.7.1
    - jmespath==0.10.0
    - jsonpickle==2.1.0
    - knack==0.9.0
    - msal==1.17.0
    - msal-extensions==0.3.1
    - msrest==0.6.21
    - msrestazure==0.6.4
    - ndg-httpsclient==0.5.1
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opacus-utils==0.2.5
    - --extra-index-url https://pkgs.dev.azure.com/ii-m365/_packaging/ii-m365/pypi/simple
    - packaging==21.3
    - pandas==1.4.1
    - paramiko==2.10.3
    - pathspec==0.9.0
    - pkginfo==1.8.2
    - portalocker==2.4.0
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pycparser==2.21
    - pydantic==1.9.0
    - pydantic-cli==4.3.0
    - pygments==2.11.2
    - pyjwt==2.3.0
    - pynacl==1.5.0
    - pyopenssl==21.0.0
    - pyparsing==3.0.7
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - secretstorage==3.3.1
    - six==1.16.0
    - tabulate==0.8.9
    - typing-extensions==4.1.1
    - urllib3==1.26.7
    - websocket-client==1.3.1
